---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  - flink.rules.yml
  - prometheus_alerts.yml
  - prometheus_rules.yml

scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: [ 'jobmanager:9249', 'taskmanager1:9249', 'taskmanager2:9249' ]
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'pushgateway'
    static_configs:
      - targets: [ 'pushgateway:9091' ]
  - job_name: 'alertmanager'
    static_configs:
      - targets: [ 'alertmanager:9093' ]
  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]