"groups":
- "name": "ecs作业未启动"
  "rules":
  - "alert": "ecs作业未启动"
    "annotations":
      "description": "ecs has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(vm_CPUUtilization{product="ecs"})
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "kvs作业未启动"
  "rules":
  - "alert": "kvs作业未启动"
    "annotations":
      "description": "kvs has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(vm_CPUUtilization{product="kvs"})
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "oss作业未启动"
  "rules":
  - "alert": "oss作业未启动"
    "annotations":
      "description": "oss has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(vm_CPUUtilization{product="oss"})
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "rds作业未启动"
  "rules":
  - "alert": "rds作业未启动"
    "annotations":
      "description": "rds has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(Queries_ps{product="rds"})
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "slb作业未启动"
  "rules":
  - "alert": "slb作业未启动"
    "annotations":
      "description": "slb has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(vm_CPUUtilization{product="slb"})
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "pushgateway未上报"
  "rules":
  - "alert": "pushgateway作业未启动"
    "annotations":
      "description": "pushgateway has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(up{job="pushgateway"} == 1)
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "prometheus未上报"
  "rules":
  - "alert": "prometheus作业未启动"
    "annotations":
      "description": "prometheus has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(up{job="prometheus"} == 1)
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "alertmanager未上报"
  "rules":
  - "alert": "alertmanager作业未启动"
    "annotations":
      "description": "alertmanager has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(up{job="alertmanager"} == 1)
    "for": "5m"
    "labels":
      "severity": "critical"
- "name": "node-exporter未上报"
  "rules":
  - "alert": "node-exporter作业未启动"
    "annotations":
      "description": "node-exporter has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(up{job="node_exporter"} == 1)
    "for": "5m"
    "labels":
      "severity": "critical"
