## Request timeout
# timeout: 5s

## Uncomment following line in order to write template from scratch (be careful!)
#no_builtin_template: true

## Customizable templates path
#templates:
#  - contrib/templates/legacy/template.tmpl

## You can also override default template using `default_message`
## The following example to use the 'legacy' template from v0.3.0
#default_message:
#  title: '{{ template "legacy.title" . }}'
#  text: '{{ template "legacy.content" . }}'

## Targets, previously was known as "profiles"
targets:
  webhook_test:
    url: https://oapi.dingtalk.com/robot/send?access_token=9166c1bd632d2953eace571a2000b2421671192bbf62f6d940c5032c3bb82a1b
    # secret for signature
    secret: SECa28a46d74c51b13a6149e96deab499e7ac761af9d6fe9d10bdb5271adf6b799f
  webhook_ruxue:
    url: https://oapi.dingtalk.com/robot/send?access_token=7f965e6da9dbf78e111ef95f7a818f8bacbece2f17ff537ffeb87cf5d245aa34
    # secret for signature
    secret: SEC9f0a39e743d376e451ce66491f00f8a17a2517958c2ef94386a7864fdf924102