---
services:
  job-cluster:
    # build: .
    image: flink:1.15.4-java8
    container_name: jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
      - "9249:9249"
    restart: always
    volumes:
      - state:/state
      - ../libs:/flink/usrlib
      - ./flink/out:/opt/flink/scripts
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
        state.checkpoints.dir: file:///state
    extra_hosts:
      - "ali-tianji-cms-transfer.data.cn-yaan-sczwhlw-d01.sls.res.inter-sctyun.com:10.81.200.186"
      - "oss_monitor_service.data.cn-yaan-sczwhlw-d01.sls.res.inter-sctyun.com:10.81.200.186"

  taskmanager1:
    # build: .
    image: flink:1.15.4-java8
    container_name: taskmanager1
    ports:
      - "9250:9249"
    restart: always
    volumes:
      - state:/state
      - ../libs:/flink/usrlib
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
        state.checkpoints.dir: file:///state
    extra_hosts:
      - "ali-tianji-cms-transfer.data.cn-yaan-sczwhlw-d01.sls.res.inter-sctyun.com:10.81.200.186"
      - "oss_monitor_service.data.cn-yaan-sczwhlw-d01.sls.res.inter-sctyun.com:10.81.200.186"

  taskmanager2:
    # build: .
    image: flink:1.15.4-java8
    container_name: taskmanager2
    ports:
      - "9251:9249"
    restart: always
    volumes:
      - state:/state
      - ../libs:/flink/usrlib
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
        state.checkpoints.dir: file:///state
    extra_hosts:
      - "ali-tianji-cms-transfer.data.cn-yaan-sczwhlw-d01.sls.res.inter-sctyun.com:10.81.200.186"
      - "oss_monitor_service.data.cn-yaan-sczwhlw-d01.sls.res.inter-sctyun.com:10.81.200.186"

volumes:
  state:
