{
 "title": "ecs主机监控",
 "description": "ECS主机监控\r\n",
 "tags": [ "CRE Dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instances",
    "query": "select vm_id from monitor.ecs_info"
   }
  ]
 },
 "panels": [
  { "title": "使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_CPUUtilization {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "MEM(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_MemoryUtilization {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "Disk(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_DiskUtilization {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{mountpoint}}\r\n"
    }
   ]
  },
  {
   "title": "Inode使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_DiskIusedUtilization {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{mountpoint}}\r\n"
    }
   ]
  },
  { "title": "饱和度", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_LoadAverage {instanceId=~\"$instances\",job=~\"pushgateway\",period=\"1min\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{period}}\r\n"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_LoadAverage {instanceId=~\"$instances\",job=~\"pushgateway\", period=\"5min\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{period}}\r\n"
    }
   ]
  },
  {
   "title": "磁盘读(KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "vm_DiskIORead {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{diskname}}\r\n"
    }
   ]
  },
  {
   "title": "磁盘写(KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "vm_DiskIOWrite {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{diskname}}\r\n"
    }
   ]
  },
  {
   "title": "网络接收(kb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "vm_InternetNetworkRX {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{netname}}\r\n"
    }
   ]
  },
  {
   "title": "网络发送(kb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "vm_InternetNetworkTX {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{netname}}\r\n"
    }
   ]
  },
  { "title": "错误", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "进程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_ProcessCount {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_TcpCount {instanceId=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\r\n",
     "legendFormat": "{{instanceId}}-{{state}}\r\n"
    }
   ]
  }
 ]
}