{
 "title": "oss Bucket监控",
 "description": "oss Bucket监控\r\n",
 "tags": [ "CRE Dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "buckets",
    "query": "select bucket_id from monitor.oss_info"
   }
  ]
 },
 "panels": [
  { "title": "存储", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "已使用存储",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "storage {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  { "title": "流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "公网流入流量(byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "recv_size {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "公网流出流量(byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "send_size {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "内网流入流量(byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "intran_recv_size {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "内网流出流量(byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "intran_send_size {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  { "title": "成功请求", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "203返回数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "success_203 {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "2xx返回数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "success_2xx {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "3xx返回数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "success_3xx {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  { "title": "错误请求", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "403返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_403 {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "404返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_404 {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "408返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_408 {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "499返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_499 {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "4xx返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_4xx {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "503返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_503 {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  },
  {
   "title": "5xx返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_5xx {bucket_name=~\"$buckets\", product=\"oss\"}\r\n",
     "legendFormat": "{{bucket_name}}\r\n"
    }
   ]
  }
 ]
}