{
 "title": "redis监控",
 "description": "Redis监控\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instances",
    "query": "select redis_id from monitor.kv_info"
   }
  ]
 },
 "panels": [
  { "title": "监控项", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "连接数使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ConnectionUsage {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "CpuUsage {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "操作失败数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "FailedCount {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "写入网络带宽(kb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "IntranetIn {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "写入带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "IntranetInRatio {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "读取网络带宽(kb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "IntranetOut {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "读取带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "IntranetOutRatio {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "MemoryUsage {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "QPS使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "QPSUsage {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "带宽配额",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "QuotaBandWidth {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "连接配额",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "QuotaConnection {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "内存配额(byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "QuotaMemory {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "QPS配额",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "QuotaQPS {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "已用连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "UsedConnection {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "已用内存(byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "UsedMemory {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  },
  {
   "title": "已用QPS数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "UsedQPS {instanceId=~\"$instances\", product=\"kv\"}\r\n",
     "legendFormat": "{{instanceId}}\r\n"
    }
   ]
  }
 ]
}