{
 "title": "slb监控",
 "description": "SLB监控\r\n",
 "tags": [ "CRE Dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instances",
    "query": "select slb_id from monitor.slb_info"
   }
  ]
 },
 "panels": [
  { "title": "监控项", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TCP新建连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "connsPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "丢失连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dropConnPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "建连失败数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "failConnPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "TCP非活跃连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "inActConnPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "流入带宽(bit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "inBitsPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "入方向丢弃流量(bit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "inDBitesPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "丢失入包数(Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "inDPktsPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "流入数据包数(Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "inPktsPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "最大并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "maxConnsPs {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "流出带宽(bit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "outBitsPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "出方向丢弃流量(bit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "outDBitesPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "丢失出包数(Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "outDPktsPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "流出数据包数(Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "outPktsPS {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "流入带宽总和",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sumInBytes {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  },
  {
   "title": "流出带宽总和",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sumOutBytes {lbId=~\"$instances\", product=\"slb\"}\r\n",
     "legendFormat": "{{lbId}}-{{vport}}\r\n"
    }
   ]
  }
 ]
}