{
 "title": "ecs主机监控",
 "description": "ECS主机监控\n",
 "tags": [ "CRE Dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instances",
    "query": "label_values(vm_LoadAverage, instanceid)"
   }
  ]
 },
 "panels": [
  { "title": "使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_CPUUtilization {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_MemoryUtilization {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_DiskUtilization {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "Inode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_DiskIusedUtilization {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  { "title": "饱和度", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_LoadAverage {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}-{{period}}\n"
    }
   ]
  },
  {
   "title": "磁盘读",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_DiskIORead {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "磁盘写",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_DiskIOWrite {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "网络接收",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_InternetNetworkRX {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "网络发送",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_InternetNetworkTX {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}-{{netname}}\n"
    }
   ]
  },
  { "title": "错误", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "进程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_ProcessCount {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vm_TcpCount {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"ecs\"}\n",
     "legendFormat": "{{instanceid}}-{{state}}\n"
    }
   ]
  }
 ]
}