{
 "title": "rds主机监控",
 "description": "RDS主机监控\n",
 "tags": [ "CRE Dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "instances", "query": "label_values(TPS, instanceId)" }
  ]
 },
 "panels": [
  { "title": "延迟", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "活动连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "active_session {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "查询数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Queries_ps {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "慢sql数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Slow_queries_ps {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  { "title": "流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "事务数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "TPS {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "事务数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "QPS {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  { "title": "使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "CpuUsage {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "MemoryUsage {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "DiskUsage {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "IO使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "IOPSUsage {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  { "title": "饱和度", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "索引使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Key_usage_ratio {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "索引查询使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Key_read_hit_ratio {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  },
  {
   "title": "索引写入使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Key_write_hit_ratio {instanceid=~\"$instances\",job=~\"pushgateway\", product=\"rds\"}\n",
     "legendFormat": "{{instanceid}}\n"
    }
   ]
  }
 ]
}