---
apiVersion: 1

deleteDatasources:
  - name: MySQL
    orgId: 1

datasources:
  - name: MySQL
    type: mysql
    url: pxc-s-unr21qvmsvitqj.mysql.rds.ops.alicloud.cqxczwy.com:3306
    user: grafana
    jsonData:
      database: monitor
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: Grafana_

